version: "3.7"

services:

    mysql:
        image: mysql:latest
        container_name: mysql-app
        command: --default-authentication-plugin=mysql_native_password
        env_file:
            - ./development.env

    website:
        build: ./web
        container_name: website-app
        ports:
            - 80:80
        volumes:
            - ./web/:/var/www/html/
        env_file:
            - ./development.env
        depends_on:
            - mysql
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin-app
        depends_on:
            - mysql
        ports:
            - 8080:80
        environment:
            - PMA_HOST=mysql-app
            - PMA_PORT=3306
        volumes:
            - /sessions
