version: "3.7"

services:

  wordpress:
    image: wordpress:latest
    container_name: wordpress-app
    depends_on:
      - mariadb
    links:
      - mariadb
    ports:
      - "1234:80"
    environment:
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: "password"
      WORDPRESS_DB_HOST: mariadb-app
      MYSQL_PORT_3306_TCP: 3306
    working_dir: /var/www/html
    volumes:
     - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
     - ./wordpress/wp-app:/var/www/html                                     # Full wordpress project
     #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name   # Plugin development
     #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name      # Theme development

  mariadb:
    image: mariadb:latest
    container_name: mariadb-app
    env_file:
      - ./development.env
    volumes:
      - ./wordpress/wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-app
    depends_on:
      - mariadb
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb-app
      - PMA_PORT=3306
    volumes:
      - /sessions

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 9080:8080

volumes:
  db_data: